### ISSUE TITLE
Serialization of meta::any

### ISSUE THREAD

**Issue by avkudr** [skypjack/meta#10]
Hi @skypjack,
Thank you for the library, it is great!

I just couldn't figure out a way to serialize meta::any. May be somehow access the underlying data and extract it?

Something like:
```
// **** Init
MyType obj;
meta::reflect<MyType >(hash("MyType "))
       .data<&MyType::some_variable>(hash("some_variable"));

auto data = meta::resolve<MyType>().data(hash("some_variable"));

// **** Write
std::cout << data(&obj).name() << ":" << data(&obj).toString();

// **** Read
std::string str; // or const char * or something else readable from file
data.set(&obj, meta::any{str});
```

Do you think it can be possible?

**Comment by skypjack** [comment]
Hi there,

I'm glad you like this library. It started as a standalone version of the [`meta` part of `EnTT`](https://github.com/skypjack/entt/tree/master/src/entt/meta) but I'm not keeping them in sync anymore.
Actually, the latter has many more features like the support for aliasing that reduces to a minimum the copies. Unfortunately, I've not enough bandwidth to port all the changes here too.

For this specific library, if you want to serialize a type, you can add a `serialize` function to the meta type. When you've an instance of `any` , you can get it's meta type, then invoke the `serialize` function and pass it the `any` itself.
Kind of:
```
any.type().resolve("serialize").invoke(any);
```
I guess you want to pass it also a stream on which to write it's data or to get a string or byte representation of the instance as a return type. This is up to you. It's a matter of defining properly the meta function and that's all.
This way you won't have to _inspect_ a type to serialize it properly since the function you attached to it already does it for you in a sense.

Does it make sense?

**Comment by avkudr** [comment]
Thanks for fast reply.

Did you mean something like this: [gist] ?(https://gist.github.com/avkudr/0223e043d48305eaa3f1b6ce876aee42)

**Comment by skypjack** [comment]
If with _this_ you meant this:
>anyB.type().func(hash("serialize")).invoke(anyB,anyB);

Yeah, more or less bu for the fact that you don't have to repeat `anyB` in the argument list afaik.

>however, how do we get the size

You're registering a meta type. What forbids you from adding a meta function that returns its size?

>I still don't have an idea to costruct meta::any from a buffer.

Can you elaborate? I've no idea of what you mean here.

**Comment by skypjack** [comment]
I guess you got your answer. If this isn't the case, feel free to reopen the issue. :+1:

**Comment by avkudr** [comment]
Yes! Thanks for your help.

At the end I just created a base class for all serializable. I'll put it below just in case someone needs it :). By the way, as I need [opencv](https://github.com/opencv/opencv) for my project anyway, I use their stream functions. The idea is that in functions read/write of our class we loop through all reflected properties and call the corresponding read/write for them.

```
template <typename Type>
static void _write(Type & f, std::size_t & id, cv::FileStorage& fs){
    fs << "p" + std::to_string(id) << f;
}

template <typename Type>
static Type _read(std::size_t & id, cv::FileNode& node){
    std::string name = "p" + std::to_string(id);
    Type t;
    node[name] >> t;
    return t;
}
```
and then
```
// should be called for all classes you want to serialize
    meta::reflect<float>(p3d_hashStr(name)) \
            .func<&impl::_read<float>>(p3d_hashStr("_read")) \
            .func<&impl::_write<float>>(p3d_hashStr("_write"))
```
### Question

There is only one problem I couldn't solve, is the reflection of ```cv::Mat``` (opencv matrix type) as the ```operator==``` doesn't return bool. 
```
meta.hpp:2039: error: cannot convert ‘cv::MatExpr’ to ‘bool’ in return
2039 |     return *static_cast<const Type *>(lhs) == *static_cast<const Type *>(rhs);
``` 
may be there is a workaround for that?

### P.S. the serialization class:
```
template<typename T>
class Serializable{

public:
    Serializable(){
    }

    virtual ~Serializable(){}

    void write(cv::FileStorage& fs) {

        // **** first we write all registered properies
        std::string nodeName = "class" + std::to_string(meta::resolve<T>().id());
        fs << nodeName << "{";
        meta::resolve<T>().data([&](meta::data data) {
            meta::func func = data.type().func(p3d_hashStr("_write"));
            if (func) {
                auto ptr = dynamic_cast<T*>(this);
                meta::any any = data.get(*ptr);
                func.invoke(any,any,data.id(),fs);
            } else {
                std::cout << "not registered for write: " << data.id() << std::endl;
            }
        });

        // **** additionally, we can write something that can't be in meta (such as cv::Mat)
        writeAdditional(fs);
        fs << "}";
    }

    void read(const cv::FileNode& node) {
        // **** first we read all registered properies
        std::string nodeName = "class" + std::to_string(meta::resolve<T>().id());
        cv::FileNode nodeL = node[nodeName];

        meta::resolve<T>().data([&](meta::data data) {
            meta::func func = data.type().func(p3d_hashStr("_read"));
            if (func) {
                auto ptr = dynamic_cast<T*>(this);
                meta::any any = data.get(*ptr);
                auto v = func.invoke(any,data.id(),nodeL);
                data.set(*ptr,v);
            } else {
                std::cout << "not registered for read: " << data.id() << std::endl;
            }
        });

        // **** additionally, we can read something that can't be in meta (such as cv::Mat)
        readAdditional(nodeL);
    }

    virtual void writeAdditional(cv::FileStorage& fs) {}
    virtual void readAdditional(const cv::FileNode& node) {}
};
```
The functions ```writeAdditional(cv::FileStorage& fs) {} ``` and ```virtual void readAdditional(const cv::FileNode& node) {}``` is what I use for ```cv::Mat``` member variables that I can't seralize with meta.

In order for this to work I had to add getters for ```identifier``` in ```meta::type``` and ```meta::data```:
```
    const size_t id() {
        return node->identifier;
    }
```

**Comment by skypjack** [comment]
>There is only one problem I couldn't solve, is the reflection of cv::Mat (opencv matrix type) as the operator== doesn't return bool.

Wut? What does it return exactly?

**Comment by avkudr** [comment]
The signature is

```CV_EXPORTS MatExpr operator == (const Mat& a, const Mat& b);```

and apparently it returns a matrix of booleans instead of a bool. There is even an issue #on their github about it.

Normally ```MatExpr``` is the result of multiplication or addition of ```Mat```.

Maybe there is a way to supply a custom compare function?

**Comment by skypjack** [comment]
>Maybe there is a way to supply a custom compare function?

Actually no. I never thought it would be necessary to be honest. I'm sorry.

**Comment by avkudr** [comment]
Ok. That’s why I added write/readAdditional functions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
